#!/usr/bin/env sage
"""
prototype_utils_v4.py

ARCHIVED / SUPERSEDED - kept for history only, nothing else imports this.
Renamed from idea2/utilsv3.py. Fourth and last exploratory utility module
in this lineage (adds LinearCode-based helpers over prototype_utils_v3.py)
before the framework moved to core/instances_generator.py and
core/LEP_prediction_and_repair_v2.py, which is what's actively used now.
"""
from copy import deepcopy
from sage.all import zero_matrix, randint, GF, FiniteField, rank, random_matrix, matrix, LinearCode
from random import random

def check_solution(Q, G1, G2):
    """
    Checks if the provided matrix Q is a valid solution to the LEP instance defined by G1 and G2.
    Returns 1 if Q is a valid monomial matrix that satisfies G2 = G1 * Q, and 0 otherwise.
    """
    if not is_monomial(Q): return 0
    if G2.rref() != (G1 * Q).rref(): return 0
    return 1

def is_monomial(Q):
    """
    Checks if the matrix Q is a monomial matrix.
    """
    if Q is None: return False
    for i in range(Q.nrows()):
        if sum(1 for j in range(Q.ncols()) if Q[i, j] != 0) != 1: return False
    for j in range(Q.ncols()):
        if sum(1 for i in range(Q.nrows()) if Q[i, j] != 0) != 1: return False
    return True

def sample_monomial_matrix(n, q):
    """
    Samples a random nxn monomial matrix over GF(q).
    """
    P = zero_matrix(FiniteField(q), n, n)
    a = [i for i in range(0, n)]
    for i in range(n-1, 0, -1):
        j = randint(0, i)
        a[i], a[j] = a[j], a[i]
    for i in range(0, n): P[i, a[i]] = randint(1, q-1)
    return P

def sample_instance(n, k, q, target_w, N=2):
    """
    Generates an LCE instance. Constructs a valid full-rank k x n generator matrix G,
    and returns N pairs of matching codewords (a_i, b_i).
    """
    # generates a random full-rank k x n generator matrix G with no zero columns
    while True:
        G = random_matrix(GF(q), k, n)
        if rank(G) == k: 
            if all(any(G[r, c] != 0 for r in range(G.nrows())) for c in range(n)):
                break

    # generate the secret monomial matrix Q and compute G' = rref(G * Q)
    Q = sample_monomial_matrix(n, q)
    G_rref = G.rref()
    G_prime_rref = (G * Q).rref()
    
    # generate N pairs of codewords (a_i, b_i) where a_i is a codeword in the space generated by G and b_i = a_i * Q
    pairs = []
    C = LinearCode(G_rref)
    
    # Dynamically find linearly independent / non-scalar-multiple low-weight codewords
    # starting from target_w up to higher weights to prevent support starvation.
    low_weight_pool = []
    seen_supports = set()
    
    current_w = target_w
    while len(low_weight_pool) < N and current_w <= n:
        for c in C:
            if c.hamming_weight() == current_w:
                cw_matrix = matrix(GF(q), 1, n, c.list())
                # Normalize the support profile to ensure we aren't just picking scalar multiples
                support_profile = tuple(1 if x != 0 else 0 for x in c.list())
                
                if support_profile not in seen_supports:
                    seen_supports.add(support_profile)
                    low_weight_pool.append(cw_matrix)
                    if len(low_weight_pool) >= N:
                        break
        current_w += 1 # Slide up weight class if the random space lacks lighter unique vectors

    import random as rand_module
    sampled_a = rand_module.sample(low_weight_pool, min(N, len(low_weight_pool)))
    
    for a_i in sampled_a:
        b_i = a_i * Q
        pairs.append([a_i, b_i])
        
    return G_rref, G_prime_rref, Q, pairs

def sample_noisy_monomial(Q, q, alpha, beta):
    """
    Introduces noise into the monomial matrix Q by flipping non-zero entries with prob alpha and flipping zero entries to random values with prob beta.
    """
    Q_noisy = deepcopy(Q)
    n = Q_noisy.nrows()
    F = GF(q)
    for i in range(n):
        for j in range(n):
            current_val = Q_noisy[i, j]
            if current_val != F(0):
                if random() < alpha:
                    all_elements = list(F)
                    all_elements.remove(current_val)
                    Q_noisy[i, j] = all_elements[randint(0, len(all_elements) - 1)]
            else:
                if random() < beta:
                    Q_noisy[i, j] = F(randint(1, q - 1))
    return Q_noisy

def solver_v2(Q_noisy, G1, G2, pairs, verbose=False):
    """
    Recover the monomial matrix Q or return None on Failure.
    Following the CBA Column Minimum-Distance Correction and Verification routine.
    Skipping non-informative zero-valued coordinates to resolve alpha with certainty.
    """
    n = Q_noisy.ncols()
    F = Q_noisy.base_ring()
    F_nonzero = [x for x in F if x != 0]

    Q_rec = zero_matrix(F, n, n)

    if verbose:
        print("\n" + "="*60)
        print("STARTING SOLVER V2 COLUMN CORRECTION ROUTINE")
        print("="*60)

    for j in range(n):
        observed_col_entries = [Q_noisy[r, j] for r in range(n)]
        candidate_scores = []
        
        for i in range(n):
            for v in F_nonzero:
                algebraic_match = True
                has_informative_pair = False
                
                for a_i, b_i in pairs:
                    if b_i[0, j] == 0:
                        continue
                    
                    has_informative_pair = True
                    if a_i[0, i] * v != b_i[0, j]:
                        algebraic_match = False
                        break
                
                if algebraic_match and has_informative_pair:
                    candidate_col = [F(0)] * n
                    candidate_col[i] = v
                    
                    d = sum(1 for x, y in zip(candidate_col, observed_col_entries) if x != y)
                    candidate_scores.append((i, v, d))
        
        if not candidate_scores:
            if verbose:
                print(f"  [Warning] Column {j} marked as uncertain (no informative pairs found).")
            continue
            
        min_d = min(score[2] for score in candidate_scores)
        min_candidates = [(i, v) for (i, v, d) in candidate_scores if d == min_d]
        
        if len(min_candidates) > 1:
            structural_filtered = [(i, v) for (i, v) in min_candidates if Q_noisy[i, j] != 0]
            if len(structural_filtered) == 1:
                min_candidates = structural_filtered

        if len(min_candidates) >= 1:
            i_opt, v_opt = min_candidates[0]
            Q_rec[i_opt, j] = v_opt
            if verbose:
                print(f"  Column {j} resolved -> Assigned Row {i_opt} with Value {v_opt} (Distance={min_d})")

    if (G1 * Q_rec).rref() == G2.rref() and is_monomial(Q_rec):
        if verbose:
            print("\nSuccess: Reconstructed matrix Q satisfies code structural equivalence.")
        return Q_rec
    else:
        if verbose:
            print("\nFailure: Reconstructed matrix does not satisfy global constraints.")
        return None

if __name__ == "__main__":
    n_length, k_dim, q_mod, w_weight = 7, 4, 29, 3
    G1, G2, Q_true, codeword_pairs = sample_instance(n_length, k_dim, q_mod, w_weight, N=20)
    print("G1 (RREF):\n", G1)
    print("G2 (RREF):\n", G2)
    print("True Q (Monomial Matrix):\n", Q_true)
    
    alpha_rate, beta_rate = 0.01, 0.2
    Q_noisy_hint = sample_noisy_monomial(Q_true, q_mod, alpha_rate, beta_rate)
    
    # Test column modification simulation safely
    Q_noisy_hint[:, 0] = 0
    print("\nNoisy Hint Matrix (Q_noisy_hint):\n", Q_noisy_hint)
    print("Codeword Pairs (a_i, b_i):")
    for idx, (a_i, b_i) in enumerate(codeword_pairs):
        print(f"  Pair {idx+1}: a_i = {a_i}, b_i = {b_i}")

    Q_recovered = solver_v2(Q_noisy_hint, G1, G2, codeword_pairs, verbose=True)
    print("\nRecovered Q (Q_recovered):\n", Q_recovered)
    
    print("\n" + "="*47)
    print(f"Recovered matrix exactly matches True Q?   : {Q_recovered == Q_true}")
    print(f"Recovered matrix is valid LCE solution?    : {bool(check_solution(Q_recovered, G1, G2))}")
    print("="*47)